name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

permissions:
  id-token: write
  attestations: write

jobs:
  upload-launchers:
    name: Upload launchers to GitHub release assets
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3
      with:
        jvm: 21
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-windows
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-mac
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-mac-arm
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-arm-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-mostly-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-arm-mostly-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-container
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-arm-container
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-jar
        path: artifacts/
    - run: ./mill -i uploadLaunchers --directory artifacts/
      env:
        UPLOAD_GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-brew-formula:
    name: Update brew formula
    needs: [upload-launchers]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: .github/scripts/scala-cli.sh .github/scripts/UpdateBrewFormula.scala
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-website-latest:
    name: Update website (snapshot)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '12'
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: .github/scripts/setup-mkdocs.sh
      - run: npm install && export PATH="$PATH:$(pwd)/node_modules/bower/bin" && ./mill -i updateWebsite
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-website:
    name: Update website
    needs: update-brew-formula
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '12'
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: .github/scripts/setup-mkdocs.sh
      - run: npm install && export PATH="$PATH:$(pwd)/node_modules/bower/bin" && ./mill -i updateWebsite
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
