name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

permissions:
  id-token: write
  attestations: write

jobs:
  generate-native-launchers:
    name: ${{ matrix.OS }} native
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
        OSSHORT: ["linux"]
        include:
          - OS: "windows-latest"
            OSSHORT: "windows"
          - OS: "macos-13"
            OSSHORT: "mac"
          - OS: "macos-14"
            OSSHORT: "mac-arm"
          - OS: "ubuntu-24.04-arm"
            OSSHORT: "linux-arm"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyLauncher --directory artifacts/
        shell: bash
      - name: Build OS packages
        run: .github/scripts/generate-os-packages.sh
        shell: bash
      - uses: actions/attest-build-provenance@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          subject-path: 'artifacts/*'
      - uses: actions/upload-artifact@v4
        with:
          name: launchers-${{ matrix.OSSHORT }}
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  generate-native-static-launcher:
    name: ${{ matrix.OS }} static native
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
        OSSHORT: ["linux"]
        include:
          - OS: "ubuntu-24.04-arm"
            OSSHORT: "linux-arm"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeStaticTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyStaticLauncher --directory artifacts/
        shell: bash
      - uses: actions/attest-build-provenance@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          subject-path: 'artifacts/*'
      - uses: actions/upload-artifact@v4
        with:
          name: launchers-${{ matrix.OSSHORT }}-static
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  generate-native-mostly-static-launcher:
    name: ${{ matrix.OS }} mostly static native
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
        OSSHORT: ["linux"]
        include:
          - OS: "ubuntu-24.04-arm"
            OSSHORT: "linux-arm"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeMostlyStaticTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyMostlyStaticLauncher --directory artifacts/
        shell: bash
      - uses: actions/attest-build-provenance@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          subject-path: 'artifacts/*'
      - uses: actions/upload-artifact@v4
        with:
          name: launchers-${{ matrix.OSSHORT }}-mostly-static
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  generate-native-container-launcher:
    name: ${{ matrix.OS }} container native
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
        OSSHORT: ["linux"]
        include:
          - OS: "ubuntu-24.04-arm"
            OSSHORT: "linux-arm"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeContainerTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyContainerLauncher --directory artifacts/
        shell: bash
      - uses: actions/attest-build-provenance@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          subject-path: 'artifacts/*'
      - uses: actions/upload-artifact@v4
        with:
          name: launchers-${{ matrix.OSSHORT }}-container
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  generate-jar-launchers:
    name: Upload JAR launchers
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3
      with:
        jvm: 21
    - name: Wait for sync to Central
      run: ./mill -i waitForSync
    - name: Copy artifacts
      run: ./mill -i copyJarLaunchers
    - uses: actions/attest-build-provenance@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        subject-path: 'artifacts/*'
    - uses: actions/upload-artifact@v4
      with:
        name: launchers-jar
        path: artifacts/
        if-no-files-found: error
        retention-days: 2

  upload-launchers:
    name: Upload launchers to GitHub release assets
    needs: [generate-native-launchers, generate-native-static-launcher, generate-native-mostly-static-launcher, generate-native-container-launcher, generate-jar-launchers]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3
      with:
        jvm: 21
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-windows
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-mac
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-mac-arm
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-arm-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-mostly-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-arm-mostly-static
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-container
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-linux-arm-container
        path: artifacts/
    - uses: actions/download-artifact@v4
      with:
        name: launchers-jar
        path: artifacts/
    - run: ./mill -i uploadLaunchers --directory artifacts/
      env:
        UPLOAD_GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-brew-formula:
    name: Update brew formula
    needs: [upload-launchers]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: .github/scripts/scala-cli.sh .github/scripts/UpdateBrewFormula.scala
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-website-latest:
    name: Update website (snapshot)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '12'
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: .github/scripts/setup-mkdocs.sh
      - run: npm install && export PATH="$PATH:$(pwd)/node_modules/bower/bin" && ./mill -i updateWebsite
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  update-website:
    name: Update website
    needs: update-brew-formula
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '12'
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3
        with:
          jvm: 21
      - run: .github/scripts/setup-mkdocs.sh
      - run: npm install && export PATH="$PATH:$(pwd)/node_modules/bower/bin" && ./mill -i updateWebsite
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
